/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "autogenerated",
      dirName: "docs"
    }
  ],
  education: [
    {
      type: "autogenerated",
      dirName: "education",
    },
  ],
  contacts: [
    {
    type: "autogenerated",
    dirName: "contacts",
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // educationSidebar: ["education/index"],
  // tutorialSidebar: {
  //   "Category A": ["intro"],
  // },
  // apiSidebar: ["education/index"],
  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   "intro",
  //   {
  //     type: "category",
  //     label: "Tutorial",
  //     items: [
  //       {
  //         type: "doc",
  //         id: "basics/event-emission",
  //         // label: 'Learn more',
  //       },
  //       {
  //         type: "doc",
  //         id: "basics/oracles",
  //         label: "Test random name",
  //       },
  //     ],
  //   },
  // ],
};

export default sidebars;
