name: Check build
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  docker-build:
    name: Build project
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
  
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - id: docker-build
        name: Build Docker image for checking project
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true
          build-args: |
              GOOGLE_TAG=${{ secrets.GOOGLE_TAG }}
              ALGOLIA_ID=${{ secrets.ALGOLIA_ID }}
              ALGOLIA_KEY=${{ secrets.ALGOLIA_KEY }}
